---
- hosts: all
  become: true
  tasks:
  - name: Set default OC admin password
    htpasswd:
      path: /etc/origin/master/htpasswd
      name: admin
      password: 'secret'
      owner: root
      group: root
      mode: 0640
    when: inventory_hostname | regex("master")
